"use client";

import { AlertTriangle, CalendarClock, ChevronRight, Clock3, Hash, History, PackageCheck, PackageSearch, Repeat2, RotateCcw, Star } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { UserHistoryItem } from "@/lib/google-sheets";
import type { DashboardActionData } from "@/lib/inventory-action-service";

type ReturnItem = DashboardActionData["returns"][number];

function dueTone(dueDate: string, now: number) {
  const remaining = new Date(dueDate).getTime() - now;
  if (remaining < 0) return { label: "เกินกำหนด", className: "border-red-200 bg-red-50 text-red-700", Icon: AlertTriangle };
  if (remaining <= 24 * 60 * 60 * 1000) return { label: "ครบกำหนดภายใน 24 ชม.", className: "border-amber-200 bg-amber-50 text-amber-700", Icon: CalendarClock };
  return { label: "กำลังยืม", className: "border-blue-200 bg-blue-50 text-blue-700", Icon: Clock3 };
}

export function MyItemsClient({ history, returns }: { history: UserHistoryItem[]; returns: ReturnItem[] }) {
  const [favorites, setFavorites] = useState<string[]>([]);
  const [now, setNow] = useState(0);
  useEffect(() => { const timer = window.setTimeout(() => { try { setFavorites(JSON.parse(localStorage.getItem("tems-favorite-equipment") || "[]")); } catch { setFavorites([]); } setNow(Date.now()); }, 0); return () => window.clearTimeout(timer); }, []);
  const active = useMemo(() => returns.map((item) => {
    const source = history.find((record) => record.movementType === "borrow" && (record.transactionIds.includes(item.transactionId) || record.items.some((part) => part.transactionId === item.transactionId)));
    return { ...item, dueDate: source?.dueDate || "", note: source?.note || "" };
  }), [history, returns]);
  const urgent = active.filter((item) => now > 0 && item.dueDate && new Date(item.dueDate).getTime() - now <= 24 * 60 * 60 * 1000);
  const recent = [...history].filter((item) => item.movementType === "borrow").slice(0, 5);
  const favoriteEntries = favorites.flatMap((name) => {
    const serials = [...new Set(active.filter((item) => item.name === name).map((item) => item.plateNumber).filter(Boolean))];
    return serials.length ? serials.map((serial) => ({ key: `${name}:${serial}`, name, serial })) : [{ key: name, name, serial: "" }];
  });
  const toggleFavorite = (name: string) => setFavorites((current) => { const next = current.includes(name) ? current.filter((item) => item !== name) : [...current, name]; localStorage.setItem("tems-favorite-equipment", JSON.stringify(next)); return next; });
  const repeat = (item: UserHistoryItem) => { localStorage.setItem("tems-borrow-repeat", JSON.stringify({ items: item.items.map((part) => ({ name: part.name, quantity: part.quantity, plateNumber: part.plateNumber || "" })), borrowerCompanyName: item.borrowerCompanyName, note: item.note })); window.location.assign("/user/borrow?repeat=1"); };

  return <main className="min-h-screen bg-slate-50 px-4 py-5 sm:px-6 sm:py-8"><div className="mx-auto max-w-7xl"><header className="linear-dark-panel overflow-hidden rounded-[28px] bg-gradient-to-br from-violet-700 via-blue-700 to-cyan-600 p-6 text-white shadow-xl sm:p-8"><p className="text-sm font-semibold text-blue-100">PERSONAL COMMAND CENTER</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">ศูนย์รายการของฉัน</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">รวมรายการที่ต้องคืน งานเร่งด่วน รายการโปรด และสิ่งที่ใช้ล่าสุดไว้ในหน้าเดียว</p><div className="mt-6 grid grid-cols-3 gap-2 sm:max-w-xl"><Stat value={active.length} label="กำลังถือครอง" /><Stat value={urgent.length} label="ต้องติดตาม" /><Stat value={favorites.length} label="รายการโปรด" /></div></header>

  <section className="mt-6 grid gap-4 lg:grid-cols-[1.35fr_0.65fr]"><div className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-md sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-red-600">งานที่ต้องติดตาม</p><h2 className="text-xl font-bold">กำลังยืมและกำหนดคืน</h2></div><Link href="/user/dashboard?action=return" className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-600 px-3 text-sm font-bold text-white"><RotateCcw className="size-4" />คืนหลายรายการ</Link></div><div className="mt-4 max-h-[34rem] space-y-3 overflow-y-auto pr-1">{active.length ? active.map((item) => { const tone = dueTone(item.dueDate, now); return <article key={item.transactionId} className="rounded-2xl border border-slate-200 p-3 transition hover:border-blue-300"><div className="flex gap-3"><span className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-xl bg-slate-50"><PackageCheck className="size-5 text-blue-600" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="truncate font-bold">{item.name}</p><p className="mt-1 text-xs text-slate-500">จาก {item.ownerCompanyName} · คงเหลือ {item.quantity.toLocaleString("th-TH")}</p></div><button type="button" onClick={() => toggleFavorite(item.name)} className={`grid size-9 shrink-0 place-items-center rounded-xl ${favorites.includes(item.name) ? "bg-amber-100 text-amber-600" : "bg-slate-100 text-slate-400"}`} aria-label="รายการโปรด"><Star className="size-4" fill={favorites.includes(item.name) ? "currentColor" : "none"} /></button></div>{item.dueDate && <span className={`mt-2 inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold ${tone.className}`}><tone.Icon className="size-3.5" />{tone.label} · {new Date(item.dueDate).toLocaleString("th-TH", { dateStyle: "medium", timeStyle: "short" })}</span>}{item.plateNumber && <p className="mt-2 text-xs font-semibold text-violet-700">Serial/ทะเบียน {item.plateNumber}</p>}</div></div></article>; }) : <Empty text="ไม่มีรายการที่กำลังยืม" />}</div></div>

  <div className="space-y-4"><Link href="/user/borrow" className="flex items-center gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 shadow-sm transition hover:bg-blue-100"><span className="grid size-11 place-items-center rounded-xl bg-blue-600 text-white"><PackageSearch className="size-5" /></span><span className="min-w-0 flex-1"><span className="block font-bold">เริ่มเบิกรายการใหม่</span><span className="text-xs text-slate-500">รองรับเลือกหลายรายการ</span></span><ChevronRight className="size-5" /></Link><div className="rounded-[24px] border border-slate-200 bg-white p-4 shadow-md"><div className="flex items-center gap-2"><Star className="size-5 fill-amber-500 text-amber-500" /><h2 className="font-bold">รายการโปรด</h2></div><div className="mt-3 flex flex-wrap gap-2">{favoriteEntries.length ? favoriteEntries.map((item) => <button key={item.key} type="button" onClick={() => { localStorage.setItem("tems-borrow-search", item.serial || item.name); window.location.href = "/user/borrow"; }} className="rounded-xl bg-amber-50 px-3 py-2 text-left text-xs font-semibold text-amber-700"><span className="block">★ {item.name}</span>{item.serial && <span className="mt-1 flex items-center gap-1 font-mono text-[11px] text-violet-700"><Hash className="size-3" />{item.serial}</span>}</button>) : <p className="text-sm text-slate-500">กดดาวจากรายการที่ถือครองหรือหน้าเบิก</p>}</div></div><Link href="/user/history" className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-md"><History className="size-5 text-amber-600" /><span className="font-bold">เปิดประวัติทั้งหมด</span><ChevronRight className="ml-auto size-5 text-slate-400" /></Link></div></section>

  <section className="mt-6 rounded-[26px] border border-slate-200 bg-white p-4 shadow-md sm:p-5"><h2 className="text-xl font-bold">ใช้ล่าสุด</h2><p className="mt-1 text-sm text-slate-500">ทำรายการเดิมซ้ำโดยระบบจะให้ตรวจจำนวนและปลายทางอีกครั้ง</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{recent.map((item) => { const serials = [...new Set(item.items.map((part) => part.plateNumber).filter(Boolean))]; return <article key={item.id} className="rounded-2xl border border-slate-200 p-4"><p className="truncate font-bold">{item.equipmentName}</p><p className="mt-1 text-xs text-slate-500">{item.items.length} รายการ · {new Date(item.date).toLocaleDateString("th-TH")}</p>{serials.length > 0 && <div className="mt-2 flex flex-wrap gap-1.5">{serials.map((serial) => <span key={serial} className="inline-flex items-center gap-1 rounded-lg bg-violet-50 px-2 py-1 font-mono text-[11px] font-semibold text-violet-700"><Hash className="size-3" />{serial}</span>)}</div>}<button type="button" onClick={() => repeat(item)} className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-violet-50 text-sm font-bold text-violet-700"><Repeat2 className="size-4" />ทำรายการซ้ำ</button></article>; })}</div>{!recent.length && <Empty text="ยังไม่มีรายการล่าสุด" />}</section></div></main>;
}

function Stat({ value, label }: { value: number; label: string }) { return <div className="rounded-2xl bg-white/10 p-3 backdrop-blur"><p className="text-2xl font-bold">{value.toLocaleString("th-TH")}</p><p className="text-[11px] text-blue-100">{label}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">{text}</div>; }
