"use client";

import { Activity, Boxes, Building2, ClipboardList, Database, LogOut, Menu, PackagePlus, RefreshCw, Search, ShieldCheck, Users, Wrench, X } from "lucide-react";
import { useCallback, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { AdminData } from "@/lib/admin-service";
import { ActionLoadingOverlay } from "@/components/ui/action-loading-overlay";
import { ThemeToggle } from "@/components/ui/theme-toggle";

type Tab = "overview" | "companies" | "users" | "equipment" | "inventory" | "transactions" | "maintenance" | "logs";
type Modal = { type: "company" | "user" | "equipment" | "inventory"; item?: Record<string, unknown> } | null;
const tabs: Array<{ id: Tab; label: string; Icon: typeof Boxes }> = [
  { id: "overview", label: "ภาพรวม", Icon: Boxes }, { id: "companies", label: "กองร้อย", Icon: Building2 }, { id: "users", label: "ผู้ใช้งาน", Icon: Users },
  { id: "equipment", label: "บัญชียุทโธปกรณ์", Icon: ClipboardList }, { id: "inventory", label: "คลังทั้งหมด", Icon: Database }, { id: "transactions", label: "เบิก / คืน", Icon: Activity },
  { id: "maintenance", label: "ซ่อมบำรุง", Icon: Wrench }, { id: "logs", label: "Audit Log", Icon: ShieldCheck },
];

export function AdminConsole({ initialData, adminName }: { initialData: AdminData; adminName: string }) {
  const router = useRouter(); const [tab, setTab] = useState<Tab>("overview"); const [query, setQuery] = useState(""); const [company, setCompany] = useState("");
  const [modal, setModal] = useState<Modal>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [menu, setMenu] = useState(false); const [refreshing, startRefresh] = useTransition();
  const keyword = query.trim().toLowerCase(); const match = useCallback((...values: unknown[]) => !keyword || values.join(" ").toLowerCase().includes(keyword), [keyword]);
  const filtered = useMemo(() => ({
    users: initialData.users.filter((x) => (!company || x.companyId === company) && match(x.firstName, x.lastName, x.email, x.rank, x.companyName)),
    inventories: initialData.inventories.filter((x) => (!company || x.companyId === company) && match(x.equipmentName, x.companyName, x.plateNumber)),
    transactions: initialData.transactions.filter((x) => match(x.id, x.equipmentName, x.owner, x.borrower, x.operator, x.status)),
    maintenance: initialData.maintenance.filter((x) => match(x.equipmentName, x.companyName, x.operator, x.status)),
    logs: initialData.logs.filter((x) => match(x.user, x.action, x.target)),
  }), [initialData, company, match]);

  async function mutate(payload: Record<string, unknown>) { setSaving(true); setMessage(""); const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error || "บันทึกไม่สำเร็จ"); return; } setModal(null); setMessage("บันทึกข้อมูลและ Audit Log เรียบร้อยแล้ว"); startRefresh(() => router.refresh()); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.replace("/"); router.refresh(); }
  const navigation = <><div className="border-b border-slate-200 p-5"><p className="text-xs font-bold tracking-[.2em] text-blue-600">TEMS COMMAND</p><h1 className="mt-1 text-xl font-bold">Admin Console</h1><p className="mt-2 text-xs text-slate-500">{adminName}</p></div><nav className="flex-1 space-y-1 p-3">{tabs.map(({id,label,Icon})=><button key={id} onClick={()=>{setTab(id);setMenu(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold ${tab===id?"linear-dark-primary bg-blue-600 text-white":"text-slate-600 hover:bg-slate-100"}`}><Icon className="size-4"/>{label}</button>)}</nav><button onClick={logout} className="logout-button m-3 flex items-center gap-3 rounded-xl bg-red-50 p-3 font-bold text-red-700"><LogOut className="size-5"/>ออกจากระบบ</button></>;

  return <div className="min-h-screen bg-slate-50 text-slate-900">{(saving||refreshing)&&<ActionLoadingOverlay message={saving?"กำลังบันทึกและสร้าง Audit Log...":"กำลังโหลดข้อมูลล่าสุด..."}/>}<aside className="fixed inset-y-0 left-0 hidden w-72 flex-col border-r border-slate-200 bg-white lg:flex">{navigation}</aside>{menu&&<div className="fixed inset-0 z-50 bg-slate-950/45 lg:hidden" onClick={()=>setMenu(false)}><aside className="flex h-full w-[84%] max-w-xs flex-col bg-white" onClick={(e)=>e.stopPropagation()}>{navigation}</aside></div>}
    <div className="lg:pl-72"><header className="sticky top-0 z-40 flex items-center gap-3 border-b border-slate-200 bg-white/90 px-4 py-3 backdrop-blur-xl"><button onClick={()=>setMenu(true)} className="grid size-10 place-items-center rounded-xl border border-slate-200 lg:hidden"><Menu className="size-5"/></button><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="ค้นหาผู้ใช้ กองร้อย ยุทโธปกรณ์ ธุรกรรม หรือ Log..." className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm"/></div><button onClick={()=>startRefresh(()=>router.refresh())} className="grid size-10 place-items-center rounded-xl border border-slate-200"><RefreshCw className="size-4"/></button><ThemeToggle/></header>
    <main className="mx-auto max-w-7xl p-4 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">ศูนย์ควบคุมส่วนกลาง</p><h2 className="text-2xl font-bold">{tabs.find(x=>x.id===tab)?.label}</h2></div>{message&&<button onClick={()=>setMessage("")} className="rounded-xl bg-blue-50 px-4 py-2 text-sm text-blue-700">{message}</button>}</div>
      {(tab==="overview"||tab==="companies")&&<CompanyGrid data={initialData} selected={company} onSelect={(id)=>{setCompany(id);setTab("inventory")}} onAdd={()=>setModal({type:"company"})}/>} 
      {tab==="overview"&&<Overview data={initialData}/>} 
      {tab==="users"&&<Section title="ผู้ใช้ทั้งหมด" action="เพิ่มผู้ใช้" onAdd={()=>setModal({type:"user"})}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.users.map(x=><Card key={x.id} onClick={()=>setModal({type:"user",item:x as unknown as Record<string,unknown>})} title={`${x.rank} ${x.firstName} ${x.lastName}`} detail={`${x.role} · ${x.companyName}`} meta={`${x.email} · ${x.phone||"ไม่มีเบอร์"}`}/>)}</div></Section>}
      {tab==="equipment"&&<Section title="บัญชียุทโธปกรณ์แม่" action="เพิ่มชนิดยุทโธปกรณ์" onAdd={()=>setModal({type:"equipment"})}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{initialData.equipments.filter(x=>match(x.name,x.category)).map(x=><Card key={x.id} onClick={()=>setModal({type:"equipment",item:x as unknown as Record<string,unknown>})} title={x.name} detail={x.category} meta={x.requirePlate?"แยกรายคัน/ทะเบียน":"นับตามจำนวน"}/>)}</div></Section>}
      {tab==="inventory"&&<Section title={company?`คลัง ${initialData.companies.find(x=>x.id===company)?.name}`:"คลังทุกกองร้อย"} action="เพิ่มรายการเข้าคลัง" onAdd={()=>setModal({type:"inventory",item:{companyId:company}})}><button onClick={()=>setCompany("")} className="mb-3 text-sm text-blue-600">แสดงทุกกองร้อย</button><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-sm"><thead><tr>{["ยุทโธปกรณ์","กองร้อย","ทะเบียน","รวม","พร้อม","ยืม","เสีย"].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{filtered.inventories.map(x=><tr key={x.id} onClick={()=>setModal({type:"inventory",item:x as unknown as Record<string,unknown>})} className="cursor-pointer border-t border-slate-100 hover:bg-blue-50"><td className="p-3 font-semibold">{x.equipmentName}</td><td>{x.companyName}</td><td>{x.plateNumber||"-"}</td><td>{x.total}</td><td className="text-emerald-600">{x.available}</td><td className="text-amber-600">{x.borrowed}</td><td className="text-red-600">{x.broken}</td></tr>)}</tbody></table></div></Section>}
      {tab==="transactions"&&<DataList rows={filtered.transactions.map(x=>({id:x.id,title:x.equipmentName,detail:`${x.owner} → ${x.borrower} · ${x.quantity} รายการ`,meta:`${x.operator} · ${x.status} · ${format(x.date)}`}))}/>} 
      {tab==="maintenance"&&<Section title="รายการแจ้งเสียและซ่อมบำรุง"><div className="space-y-3">{filtered.maintenance.map(x=><div key={x.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{x.equipmentName}</h3><p className="text-sm text-slate-500">{x.companyName} · {x.operator} · {x.quantity} รายการ</p><p className="mt-1 text-sm">{x.note||"-"}</p></div><select value={x.status} onChange={(e)=>mutate({action:"maintenance-status",id:x.id,status:e.target.value})} className="h-10 rounded-xl border border-slate-200 px-2"><option>Reported</option><option>Inspecting</option><option>Repairing</option><option>Completed</option></select></div></div>)}</div></Section>}
      {tab==="logs"&&<DataList rows={filtered.logs.map(x=>({id:x.id,title:x.action,detail:`ผู้ดำเนินการ: ${x.user}${x.details?` · ${x.details}`:""}`,meta:`เป้าหมาย ${x.target} · ${format(x.timestamp)}`}))}/>} 
    </main></div>{modal&&<EditModal modal={modal} data={initialData} onClose={()=>setModal(null)} onSave={mutate}/>}</div>;
}

function Overview({data}:{data:AdminData}) { const total=data.companies.reduce((s,x)=>s+x.total,0); const metrics=[{label:"ยุทโธปกรณ์รวม",value:total,Icon:Boxes},{label:"ผู้ใช้งาน",value:data.users.length,Icon:Users},{label:"กำลังยืม",value:data.transactions.filter(x=>x.status.toLowerCase()==="borrowed").length,Icon:Activity},{label:"แจ้งซ่อม",value:data.maintenance.filter(x=>x.status!=="Completed").length,Icon:Wrench}]; return <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(({label,value,Icon})=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-md"><Icon className="size-5 text-blue-600"/><p className="mt-5 text-sm text-slate-500">{label}</p><p className="text-3xl font-bold">{value.toLocaleString("th-TH")}</p></div>)}</section> }
function CompanyGrid({data,selected,onSelect,onAdd}:{data:AdminData;selected:string;onSelect:(id:string)=>void;onAdd:()=>void}) { return <Section title="ทุกกองร้อย" action="เพิ่มกองร้อย" onAdd={onAdd}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.companies.map(x=><button key={x.id} onClick={()=>onSelect(x.id)} className={`rounded-2xl border bg-white p-5 text-left shadow-md transition hover:-translate-y-1 ${selected===x.id?"border-blue-500":"border-slate-200"}`}><div className="flex justify-between"><Building2 className="size-6 text-blue-600"/><span className="text-xs text-slate-500">{x.users} ผู้ใช้</span></div><h3 className="mt-4 text-lg font-bold">{x.name}</h3><div className="mt-4 grid grid-cols-4 gap-2 text-center text-xs"><Stat n={x.total} l="รวม"/><Stat n={x.available} l="พร้อม"/><Stat n={x.borrowed} l="ยืม"/><Stat n={x.broken} l="เสีย"/></div></button>)}</div></Section> }
const Stat=({n,l}:{n:number;l:string})=><div><p className="text-lg font-bold">{n}</p><p className="text-slate-500">{l}</p></div>;
function Section({title,action,onAdd,children}:{title:string;action?:string;onAdd?:()=>void;children:React.ReactNode}) { return <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h3 className="text-lg font-bold">{title}</h3>{action&&<button onClick={onAdd} className="flex items-center gap-2 rounded-full bg-blue-600 px-4 py-2 text-sm font-bold text-white"><PackagePlus className="size-4"/>{action}</button>}</div>{children}</section> }
function Card({title,detail,meta,onClick}:{title:string;detail:string;meta:string;onClick:()=>void}) { return <button onClick={onClick} className="rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-md hover:border-blue-300"><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-blue-600">{detail}</p><p className="mt-2 truncate text-xs text-slate-500">{meta}</p></button> }
function DataList({rows}:{rows:Array<{id:string;title:string;detail:string;meta:string}>}) { return <div className="mt-6 space-y-3">{rows.map(x=><div key={x.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-bold">{x.title}</h3><p className="mt-1 text-sm text-slate-600">{x.detail}</p><p className="mt-2 text-xs text-slate-400">{x.meta}</p></div>)}</div> }
const format=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short"}).format(d)};

function EditModal({modal,data,onClose,onSave}:{modal:NonNullable<Modal>;data:AdminData;onClose:()=>void;onSave:(x:Record<string,unknown>)=>void}) { const item=modal.item||{}; const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();onSave(Object.fromEntries(new FormData(e.currentTarget).entries()))}; return <div className="popup-backdrop fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-6"><form onSubmit={submit} className="popup-panel max-h-[92dvh] w-full max-w-xl overflow-y-auto rounded-t-[30px] bg-white p-5 sm:rounded-[30px]"><div className="flex justify-between"><h2 className="text-xl font-bold">จัดการ{modal.type}</h2><button type="button" onClick={onClose}><X/></button></div><input type="hidden" name="action" value={`save-${modal.type}`}/><input type="hidden" name="id" value={String(item.id||"")}/><div className="mt-5 grid gap-4 sm:grid-cols-2">{modal.type==="company"&&<Input name="name" label="ชื่อกองร้อย" value={item.name}/>} {modal.type==="user"&&<><Select name="companyId" label="กองร้อย" value={item.companyId} options={data.companies.map(x=>[x.id,x.name])}/><Select name="role" label="สิทธิ์" value={item.role||"User"} options={[["User","User"],["Admin","Admin"]]}/><Input name="rank" label="ยศ" value={item.rank}/><Input name="firstName" label="ชื่อ" value={item.firstName}/><Input name="lastName" label="นามสกุล" value={item.lastName}/><Input name="email" label="อีเมลเข้าสู่ระบบ" value={item.email} type="email"/><Input name="phone" label="เบอร์โทร" value={item.phone}/><Input name="gmail" label="Gmail กู้คืน" value={item.gmail} type="email"/><Input name="password" label={item.id?"รหัสผ่านใหม่ (เว้นว่างได้)":"รหัสผ่านเริ่มต้น"} type="password"/> </>} {modal.type==="equipment"&&<><Input name="name" label="ชื่อยุทโธปกรณ์" value={item.name}/><Input name="category" label="หมวดหมู่" value={item.category}/><label className="flex items-center gap-3"><input type="checkbox" name="requirePlate" value="true" defaultChecked={Boolean(item.requirePlate)}/> แยกรายคัน/ทะเบียน</label></>} {modal.type==="inventory"&&<><Select name="companyId" label="กองร้อย" value={item.companyId} options={data.companies.map(x=>[x.id,x.name])}/><Select name="equipmentId" label="ยุทโธปกรณ์" value={item.equipmentId} options={data.equipments.map(x=>[x.id,x.name])}/><Input name="plateNumber" label="ทะเบียน/หมายเลข" value={item.plateNumber}/><Input name="total" label="รวม" value={item.total||0} type="number"/><Input name="available" label="พร้อมใช้" value={item.available||0} type="number"/><Input name="borrowed" label="ถูกยืม" value={item.borrowed||0} type="number"/><Input name="broken" label="ชำรุด" value={item.broken||0} type="number"/></>}</div><button className="mt-6 h-12 w-full rounded-full bg-blue-600 font-bold text-white">บันทึกและสร้าง Audit Log</button></form></div> }
function Input({name,label,value="",type="text"}:{name:string;label:string;value?:unknown;type?:string}) { return <label className="block"><span className="mb-1 block text-sm font-semibold">{label}</span><input name={name} type={type} defaultValue={String(value)} required={!label.includes("เว้นว่าง")&&name!=="plateNumber"&&name!=="phone"&&name!=="gmail"} className="h-11 w-full rounded-xl border border-slate-200 px-3"/></label> }
function Select({name,label,value="",options}:{name:string;label:string;value?:unknown;options:string[][]}) { return <label><span className="mb-1 block text-sm font-semibold">{label}</span><select name={name} defaultValue={String(value)} className="h-11 w-full rounded-xl border border-slate-200 px-3">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label> }
